apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RanM-DevOpsLabs/GitOpsLabs.git
    targetRevision: HEAD
    path: ArgoCD/.gitops/lab
  destination:
    server: https://kubernetes.default.svc
    namespace: lab