apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RanM-DevOpsLabs/GitOpsLabs.git
    targetRevision: HEAD
    path: ArgoCD/.gitops/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true